[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "confirm wing avocado write soon gravity awesome renew best drive fury group parade wood theme occur breeze rib truck forward bulk hunt material riot"
